added normalization and skull stripping
nlpeUB/mialab pull request #4
Opened 2024-10-30 08:45 UTC by DAck29

2024-10-30 10:49 UTC, alicjak1519 requested changes
lgtm, maybe we can just update the warning message, because the previous one is not true anymore thanks to this PR :)

2024-10-30 10:49 UTC, alicjak1519 commented on mialab/filtering/preprocessing.py
> +            warnings.warn('No skull-stripping implemented. Returning unprocessed image.')
```suggestion
            warnings.warn('No brain mask for skull-stripping provided. Returning unprocessed image.')
```

2024-10-31 09:07 UTC, DAck29 commented on mialab/filtering/preprocessing.py
> +            warnings.warn('No skull-stripping implemented. Returning unprocessed image.')
Sounds good.

2024-10-31 13:27 UTC, alicjak1519 approved these changes
👌

2024-11-05 21:23 UTC, merged